import type { NextPage } from "next";
import Head from "next/head";

import {
  About,
  Footer,
  Header,
  Skills,
  Testimonial,
  Work,
} from "../src/container";
import { Navbar } from "../src/components";

const Home: NextPage = () => {
  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <About />
      <Work />
      <Skills />
      <Testimonial />
      <Footer />
    </div>
  );
};

export default Home;
